travis:
  secure:
    BINSTAR_TOKEN: FOZm3a+WUpPAEfZWRLk7yPwxXMlSZgNvpWkscQlg3gcFad9BQV2E6RPT9KEMmZhCK6WkKRGCrZIsK7BxGDRI6ZlanX2bVa7IIRKxpnirABsyphlWCHRhPmsrOL07haaxFi1R6sRRSAG9mPd5wiE8gjXWNgs4uaQGfLE7huFIq+2ZQ3/lONt7qcU9/AUCDOS9ZevKChsY98XDLQrfjT19j7d4ERYqyDNh1rJ4bv51sOW8xcwQoRWAdQV1YC5bPB4YvMRToB4AG8KyOMBwOOdV6R0DyH8VeIHYQaumOfxXAKMZsJITCCmngqPZ2frOTkRqJrcZpakghIgWlyccDnav5mtD4agMUl/oK+DPyblY2vi4KGu4pu+LpF7H8TzDxoyfI5aYl68Szk1B+CYDsJBa6Jcr0G/NAWq9MvsWZcMnPG/oz1MMbjYzHdDiR+1FJsIzCj+hBCwWEdv98sEGbGvHdfclUuN+ljh7omm2LwuQ6Yd1DWGE7NFCJxZ3RU4mLLWJv//oK7bQzuL7+MMn5MpEMRKS7gW0IN3B6efHlIeQUzjM2F3S9rjzwrBXvMoGGn9WdkTqb8SVe0hvDIPOzcS2UWjN9EodyZOLDnlzeLEPQyHvnaaRRfygM9aVc9go/v5PAuW/dFsLVrS+U73InnQ3lHujhT2xliC5ZrVAem5Ysm0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
